<a href="https://colab.research.google.com/github/sajjkavinda/ML-based-Intrution-detection-system/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning

This notebook performs the data cleaning stage of the proposed IDS.

The preprocessing pipeline consists of:

1. Creating a reproducible subset of the dataset
2. Removing duplicate records
3. Handling missing and infinite values
4. Converting data types
5. Removing unnecessary features
6. Encoding the target variable
7. Saving the cleaned dataset for feature engineering

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Import libraries

In [ ]:
import pandas as pd
import numpy as np

from pathlib import Path

import warnings
warnings.filterwarnings("ignore")

Set dataset and output paths

In [ ]:
PROJECT_DIR = Path("/content/drive/MyDrive/MSc_Dissertation")

DATASET_DIR = PROJECT_DIR / "Dataset"

PROCESSED_DIR = DATASET_DIR / "Processed"

PROCESSED_DIR.mkdir(exist_ok=True)

DATA_FILES = [
    "Friday-16-02-2018_TrafficForML_CICFlowMeter.csv",
    "Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv",
    "Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv",
    "Friday-23-02-2018_TrafficForML_CICFlowMeter.csv",
    "Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv"
]

Load the dataset

In [ ]:
dfs = []

for file in DATA_FILES:

    file_path = DATASET_DIR / file

    print(f"Loading: {file}")

    temp_df = pd.read_csv(
        file_path,
        low_memory=False
    )

    print("Shape:", temp_df.shape)

    dfs.append(temp_df)


# Combine all selected days
df = pd.concat(
    dfs,
    ignore_index=True
)


print("\nCombined dataset shape:")
print(df.shape)


print("\nOriginal label distribution:")
print(df["Label"].value_counts())

Loading: Friday-16-02-2018_TrafficForML_CICFlowMeter.csv
Shape: (1048575, 80)
Loading: Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv
Shape: (1048575, 80)
Loading: Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv
Shape: (1048575, 80)
Loading: Friday-23-02-2018_TrafficForML_CICFlowMeter.csv
Shape: (1048575, 80)
Loading: Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv
Shape: (613104, 80)

Combined dataset shape:
(4807404, 80)

Original label distribution:
Label
Benign                      3395891
DDOS attack-HOIC             686012
DoS attacks-Hulk             461912
DoS attacks-SlowHTTPTest     139890
Infilteration                 68871
DoS attacks-GoldenEye         41508
DoS attacks-Slowloris         10990
DDOS attack-LOIC-UDP           1730
Brute Force -Web                362
Brute Force -XSS                151
SQL Injection                    53
Label                            34
Name: count, dtype: int64

Create a subset from the dataset

Subset size = 600000 rows

In [ ]:
dfs = []

for file in DATA_FILES:

    file_path = DATASET_DIR / file

    print(f"Loading: {file}")

    temp_df = pd.read_csv(
        file_path,
        low_memory=False
    )

    print("Shape:", temp_df.shape)

    dfs.append(temp_df)


df = pd.concat(
    dfs,
    ignore_index=True
)


print("\nCombined dataset shape:")
print(df.shape)


print("\nOriginal label distribution:")
print(df["Label"].value_counts())

Loading: Friday-16-02-2018_TrafficForML_CICFlowMeter.csv
Shape: (1048575, 80)
Loading: Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv
Shape: (1048575, 80)
Loading: Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv
Shape: (1048575, 80)
Loading: Friday-23-02-2018_TrafficForML_CICFlowMeter.csv
Shape: (1048575, 80)
Loading: Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv
Shape: (613104, 80)

Combined dataset shape:
(4807404, 80)

Original label distribution:
Label
Benign                      3395891
DDOS attack-HOIC             686012
DoS attacks-Hulk             461912
DoS attacks-SlowHTTPTest     139890
Infilteration                 68871
DoS attacks-GoldenEye         41508
DoS attacks-Slowloris         10990
DDOS attack-LOIC-UDP           1730
Brute Force -Web                362
Brute Force -XSS                151
SQL Injection                    53
Label                            34
Name: count, dtype: int64

In [ ]:
subset_size = 600000

df = (
    df.groupby("Label", group_keys=False)
      .apply(
          lambda x: x.sample(
              n=min(
                  len(x),
                  int(len(x) / len(df) * subset_size)
              ),
              random_state=42
          )
      )
      .reset_index(drop=True)
)

print("Subset shape:")
print(df.shape)

print("\nLabel distribution:")
print(df["Label"].value_counts())

Subset shape:
(599994, 80)

Label distribution:
Label
Benign                      423832
DDOS attack-HOIC             85619
DoS attacks-Hulk             57650
DoS attacks-SlowHTTPTest     17459
Infilteration                 8595
DoS attacks-GoldenEye         5180
DoS attacks-Slowloris         1371
DDOS attack-LOIC-UDP           215
Brute Force -Web                45
Brute Force -XSS                18
SQL Injection                    6
Label                            4
Name: count, dtype: int64

Handle infinite values

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)

Handle missing values

In [ ]:
print(df.isnull().sum().sum())

df.dropna(inplace=True)

print(df.shape)

3880
(597794, 80)

Remove the column Timestamp since it's not required for IDS

In [ ]:
df.drop(columns=["Timestamp"], inplace=True)

Records are in objects format. Convert them to numeric format except labels

In [ ]:
for col in df.columns:

    if col != "Label":

        df[col] = pd.to_numeric(df[col], errors="coerce")

Remove missing values

In [ ]:
df.dropna(inplace=True)

print(df.shape)

(597790, 79)

Encode labels

In [ ]:
df["Label"].value_counts()

Label
Benign                      421688
DDOS attack-HOIC             85619
DoS attacks-Hulk             57650
DoS attacks-SlowHTTPTest     17459
Infilteration                 8539
DoS attacks-GoldenEye         5180
DoS attacks-Slowloris         1371
DDOS attack-LOIC-UDP           215
Brute Force -Web                45
Brute Force -XSS                18
SQL Injection                    6
Name: count, dtype: int64

In [ ]:
# Remove leading/trailing spaces
df["Label"] = df["Label"].astype(str).str.strip()

# Encode labels
df["Label"] = df["Label"].map({
    "Benign": 0,
    "DoS attacks-Hulk": 1,
    "DoS attacks-SlowHTTPTest": 1
})

print(df["Label"].value_counts())

Label
0.0    421688
1.0     75109
Name: count, dtype: int64

Remove duplicate records

In [ ]:
duplicate_count = df.duplicated().sum()

print(f"Duplicates before removal: {duplicate_count}")

df = df.drop_duplicates()

print(f"Shape after duplicate removal: {df.shape}")

Duplicates before removal: 115563
Shape after duplicate removal: (482227, 79)

In [ ]:
print("Missing values:", df.isnull().sum().sum())
print("Duplicates:", df.duplicated().sum())
print("Shape:", df.shape)
df["Label"].value_counts()

Missing values: 56716
Duplicates: 0
Shape: (482227, 79)

Label
0.0    390228
1.0     35283
Name: count, dtype: int64

Save the cleaned subset

In [ ]:
from pathlib import Path

OUTPUT_FILE = Path(
    "/content/drive/MyDrive/MSc_Dissertation/Dataset/Processed/cleaned_dataset.csv"
)

df.to_csv(OUTPUT_FILE, index=False)

print("Saved successfully:")
print(OUTPUT_FILE)

Saved successfully:
/content/drive/MyDrive/MSc_Dissertation/Dataset/Processed/cleaned_dataset.csv